### ISSUE TITLE
[REFACTOR] 모듈 분리 작업

### ISSUE THREAD

**Issue by yongyongkr** [WeGoUpToMars/mars-payment-server#33]
## Description

마스 프로젝트를 멀티 모듈 프로젝트로 만듭니다.
총 7개의 모듈로 분리되며, 코어 모듈과 아래의 6개 모듈로 분리합니다.

## TODO List

- [ ] 유저 서비스 모듈 분리
- [ ] 상품 서비스 모듈 분리
- [ ] 주문 서비스 모듈 분리
- [ ] 결제 서비스 모듈 분리
- [ ] 상점 서비스 모듈 분리
- [ ] 외부 API 연동 인프라 모듈 분리

**Comment by guswns3371** [comment]
해당 작업은 추후 프로젝트에 MSA 아키텍쳐 도입할 때에 작업 진행하도록 하겠습니다
